spring:
  application:
    name: reward-service
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
server:
  port: 443
  ssl:
    key-store: keystore.p12
    key-store-password: Ravish01
    keyStoreType: PKCS12
    keyAlias: rks  
rewards:
  point:
    default-point: 0
    first-limit: 1
    second-limit: 2
    duration: -3
  price:
    first-lower-limit: 50
    first-upper-limit: 100
    second-lower-limit: 100
    
  
