spring:
  application:
    name: reward-service
  jpa:
    database: h2
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: create-drop
      use-new-id-generator-mappings: true
    defer-datasource-initialization: true
server:
  port: 8082
rewards:
  point:
    default-point: 0
    first-limit: 1
    second-limit: 2
  price:
    first-lower-limit: 50
    first-upper-limit: 100
    second-lower-limit: 100
    
  
